# Generated by Django 4.1.2 on 2022-11-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Totalamount', models.IntegerField()),
                ('percentage', models.IntegerField(default=12)),
                ('adminPercentageamount', models.IntegerField()),
            ],
        ),
    ]
