# Generated by Django 4.1.2 on 2022-11-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_adminpercentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminPercentage',
        ),
    ]
