# Generated by Django 4.1.2 on 2022-11-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_marks_quiz_marks_question_no_alter_marks_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalmarks',
            name='user',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.DeleteModel(
            name='TotalMarks',
        ),
    ]
