# Generated by Django 4.1.2 on 2022-11-12 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Totalamount', models.IntegerField()),
                ('percentage', models.IntegerField(default=12)),
                ('adminPercentageamount', models.IntegerField()),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.order')),
            ],
        ),
    ]
