# Generated by Django 4.1.2 on 2022-10-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutors',
            old_name='email',
            new_name='emails',
        ),
    ]
