# Generated by Django 4.1.2 on 2022-10-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_email_tutors_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutors',
            old_name='emails',
            new_name='email',
        ),
    ]
