# Generated by Django 4.1.2 on 2022-11-04 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_course_options_alter_tutors_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignmentsPDF',
            field=models.FileField(null=True, upload_to='tutor/assignments'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
