# Generated by Django 4.1.2 on 2022-11-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_enrolledcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='chapter_videos'),
        ),
    ]
