# Generated by Django 4.1.2 on 2022-11-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_chapter_no_alter_chapter_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chapter_videos'),
        ),
    ]
