# Generated by Django 4.1.2 on 2022-11-11 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_alter_chapter_no_alter_chapter_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentsname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assignments')),
                ('chaptername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chapter')),
                ('studentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tutors')),
            ],
        ),
    ]
