# Generated by Django 4.1.2 on 2022-11-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userassignment',
            options={'verbose_name_plural': '6.User Assignments'},
        ),
        migrations.AddField(
            model_name='userassignment',
            name='userassignment',
            field=models.FileField(null=True, upload_to='user/assignments'),
        ),
    ]
