# Generated by Django 4.1.2 on 2022-11-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_userassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourses',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='enrolledcourses',
            name='prince',
            field=models.IntegerField(null=True),
        ),
    ]
