# Generated by Django 4.1.2 on 2022-11-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_enrolledcourses_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAssignment',
        ),
    ]
