# Generated by Django 4.1.2 on 2022-11-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_quiz_quizquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_mark',
            field=models.IntegerField(null=True),
        ),
    ]
