# Generated by Django 4.1.2 on 2022-11-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_quiz_total_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='total_mark',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
