# Generated by Django 4.1.2 on 2022-11-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_quiz_total_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('answer', models.CharField(max_length=200)),
                ('marks', models.IntegerField()),
                ('QuizQuestions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizquestions')),
            ],
        ),
    ]
