# Generated by Django 4.1.2 on 2022-11-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_certificate_usercertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usercertificate', models.FileField(upload_to='user/certificate')),
                ('success', models.BooleanField(default=False)),
                ('certicate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.certificate')),
            ],
            options={
                'verbose_name_plural': '11.postCertificate',
            },
        ),
    ]
