# Generated by Django 4.1.2 on 2022-11-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_postcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='is_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
