# Generated by Django 4.1.2 on 2022-11-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_certificate_is_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcertificate',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
