# Generated by Django 4.1.2 on 2022-11-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_postcertificate_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
